In [2]:
import pandas as pd
#read the data1

data1=pd.read_csv('GSE262814_raw_counts_GRCh38.p13_NCBI.tsv', sep='\t')

#load the data1
data1

,GeneID,GSM8179740,GSM8179741,GSM8179743,GSM8179744,GSM8179745,GSM8179747,GSM8179751,GSM8179752,GSM8179754,GSM8179757,GSM8179758
0,100287102,5,35,16,9,48,9,29,28,12,16,10
1,653635,156,322,186,297,642,116,358,177,217,175,242
2,102466751,2,5,6,4,10,2,10,4,3,2,6
3,107985730,0,0,0,0,0,0,0,0,0,0,0
4,100302278,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
39371,4541,2495,4283,3602,6422,9461,1906,7387,5932,3668,2764,1276
39372,4556,185,339,225,470,777,165,523,444,259,214,119
39373,4519,9573,21810,15739,25823,29267,7972,24741,21566,14127,11818,6739
39374,4576,16,17,30,38,62,9,15,33,11,12,4
39375,4571,8,15,11,21,44,5,17,15,10,11,4

In [3]:
data2=pd.read_csv('GSE262815_raw_counts_GRCh38.p13_NCBI.tsv', sep='\t')

#load the data2
data2

,GeneID,GSM8179760,GSM8179762,GSM8179763,GSM8179764,GSM8179766,GSM8179767,GSM8179768,GSM8179769,GSM8179770,GSM8179772,GSM8179774,GSM8179775,GSM8179778
0,100287102,6,22,12,3,30,10,33,15,28,43,16,53,13
1,653635,163,223,116,156,247,148,722,133,145,272,259,965,397
2,102466751,2,3,2,2,3,4,17,1,2,6,3,20,7
3,107985730,0,0,0,0,0,0,0,0,0,0,0,0,0
4,100302278,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39371,4541,2642,5264,2256,3673,7315,2811,2255,2059,2299,8997,4179,5985,2382
39372,4556,188,403,155,264,607,245,198,142,210,697,321,493,193
39373,4519,10539,27304,10448,14613,28539,11207,11231,8946,10602,33409,16122,26412,11363
39374,4576,18,17,25,15,42,11,8,10,18,40,10,18,9
39375,4571,15,9,6,17,25,11,11,5,13,25,10,15,10

In [4]:
data3=pd.read_csv('GSE262828_raw_counts_GRCh38.p13_NCBI.tsv', sep='\t')

#load the data3
data3

,GeneID,GSM8180110,GSM8180111,GSM8180113,GSM8180114,GSM8180115,GSM8180118,GSM8180120,GSM8180121,GSM8180122,...,GSM8180179,GSM8180182,GSM8180183,GSM8180184,GSM8180186,GSM8180187,GSM8180188,GSM8180192,GSM8180193,GSM8180195
0,100287102,44,24,81,73,39,34,38,87,27,...,32,31,27,12,53,35,126,77,31,23
1,653635,292,328,287,376,351,248,417,473,411,...,360,434,606,356,353,407,469,408,311,469
2,102466751,4,4,1,4,2,1,4,12,3,...,3,6,5,3,2,5,2,7,1,3
3,107985730,0,2,0,1,1,0,0,0,0,...,0,0,1,0,0,2,0,0,1,0
4,100302278,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39371,4541,627,162,281,240,299,223,167,279,214,...,269,159,204,41,239,112,340,112,59,14775
39372,4556,4,1,5,3,6,4,6,7,2,...,10,2,1,0,5,5,4,5,0,413
39373,4519,10351,1874,4689,4079,4706,5034,2665,3393,3271,...,3970,2603,2242,956,3687,1964,7754,2282,1310,62516
39374,4576,16,4,29,13,21,25,26,16,15,...,23,16,17,11,14,8,37,26,8,116
39375,4571,57,12,46,40,41,42,29,29,27,...,124,93,39,11,31,11,85,34,12,848

In [6]:
merged_data=pd.merge(data1,data2,on='GeneID')
final_data=pd.merge(merged_data,data3,on='GeneID')

final_data

,GeneID,GSM8179740,GSM8179741,GSM8179743,GSM8179744,GSM8179745,GSM8179747,GSM8179751,GSM8179752,GSM8179754,...,GSM8180179,GSM8180182,GSM8180183,GSM8180184,GSM8180186,GSM8180187,GSM8180188,GSM8180192,GSM8180193,GSM8180195
0,100287102,5,35,16,9,48,9,29,28,12,...,32,31,27,12,53,35,126,77,31,23
1,653635,156,322,186,297,642,116,358,177,217,...,360,434,606,356,353,407,469,408,311,469
2,102466751,2,5,6,4,10,2,10,4,3,...,3,6,5,3,2,5,2,7,1,3
3,107985730,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,0,0,1,0
4,100302278,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39371,4541,2495,4283,3602,6422,9461,1906,7387,5932,3668,...,269,159,204,41,239,112,340,112,59,14775
39372,4556,185,339,225,470,777,165,523,444,259,...,10,2,1,0,5,5,4,5,0,413
39373,4519,9573,21810,15739,25823,29267,7972,24741,21566,14127,...,3970,2603,2242,956,3687,1964,7754,2282,1310,62516
39374,4576,16,17,30,38,62,9,15,33,11,...,23,16,17,11,14,8,37,26,8,116
39375,4571,8,15,11,21,44,5,17,15,10,...,124,93,39,11,31,11,85,34,12,848

In [7]:
# Remove leading and trailing whitespace from column names in the DataFrame
final_data.columns = final_data.columns.str.strip()

final_data

,GeneID,GSM8179740,GSM8179741,GSM8179743,GSM8179744,GSM8179745,GSM8179747,GSM8179751,GSM8179752,GSM8179754,...,GSM8180179,GSM8180182,GSM8180183,GSM8180184,GSM8180186,GSM8180187,GSM8180188,GSM8180192,GSM8180193,GSM8180195
0,100287102,5,35,16,9,48,9,29,28,12,...,32,31,27,12,53,35,126,77,31,23
1,653635,156,322,186,297,642,116,358,177,217,...,360,434,606,356,353,407,469,408,311,469
2,102466751,2,5,6,4,10,2,10,4,3,...,3,6,5,3,2,5,2,7,1,3
3,107985730,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,2,0,0,1,0
4,100302278,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39371,4541,2495,4283,3602,6422,9461,1906,7387,5932,3668,...,269,159,204,41,239,112,340,112,59,14775
39372,4556,185,339,225,470,777,165,523,444,259,...,10,2,1,0,5,5,4,5,0,413
39373,4519,9573,21810,15739,25823,29267,7972,24741,21566,14127,...,3970,2603,2242,956,3687,1964,7754,2282,1310,62516
39374,4576,16,17,30,38,62,9,15,33,11,...,23,16,17,11,14,8,37,26,8,116
39375,4571,8,15,11,21,44,5,17,15,10,...,124,93,39,11,31,11,85,34,12,848

In [9]:
final_data.shape

(39376, 65)

In [10]:
type(final_data)

pandas.core.frame.DataFrame

In [11]:
# Save the DataFrame(final_data) to a TSV file
final_data.to_csv('merged_data.tsv', sep='\t', index=False)